### ISSUE TITLE
运行 predict.py 时报错 “No module named 'sklearn.preprocessing.data'”

### ISSUE THREAD

**Issue by zfqy** [Renovamen/Speech-Emotion-Recognition#29]
环境中的版本为 scikit-learn==1.0.2，和 requirement 保持一致
在配置完 opensmile 路径后，也能够成功生成 predict.csv（虽然有一些错误提示）
但最后报错误 No module named 'sklearn.preprocessing.data'

进一步研究发现错误来源是：
joblib.load('./checkpoints/SCALER_OPENSMILE.m')
核查版本 joblib==1.1.0 和文件路径也没有错误

实在找不到解决方案了，请指点
感谢！

Opensmile extracting...
Opensmile cmd:  cd C:/Users/aidi/Desktop/opensmile/opensmile-3.0-win-x64//bin && SMILExtract -C C:/Users/aidi/Desktop/opensmile/opensmile-3.0-win-x64/config/is09-13/IS09_emotion.conf -I C:\Users\aidi\Desktop\Speech-Emotion-Recognition\samples\201_angry.wav -O C:\Users\aidi\Desktop\Speech-Emotion-Recognition\features/6-category/opensmile_casia/single_feature.csv -appendarff 0
(MSG) [2] SMILExtract: openSMILE starting!
(MSG) [2] SMILExtract: config file is: C:/Users/aidi/Desktop/opensmile/opensmile-3.0-win-x64/config/is09-13/IS09_emotion.conf
(MSG) [2] cComponentManager: successfully registered 103 component types.
(MSG) [2] instance 'lldsink': No filename given, disabling this sink component.
(MSG) [2] instance 'lldhtksink': No filename given, disabling this sink component.
(MSG) [2] instance 'lldarffsink': No filename given, disabling this sink component.
(MSG) [2] instance 'csvsink': No filename given, disabling this sink component.
(MSG) [2] instance 'htksink': No filename given, disabling this sink component.
(MSG) [2] instance 'arffsink': writing ARFF header (384 features)...
(MSG) [2] cComponentManager: successfully finished createInstances (25 component instances were finalised, 1 data memories were finalised)
(MSG) [2] cComponentManager: starting single thread processing loop
(MSG) [2] cComponentManager: Processing finished! System ran for 147 ticks.
Opensmile extract done.
Traceback (most recent call last):
  File "C:\Users\aidi\anaconda3\envs\SER\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\aidi\anaconda3\envs\SER\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "C:\Users\aidi\anaconda3\envs\SER\lib\pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "C:\Users\aidi\anaconda3\envs\SER\lib\pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\aidi\anaconda3\envs\SER\lib\pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.preprocessing.data'

**Comment by v-yunbin** [comment]
met same error，too

**Comment by Vontean** [comment]
Metoo, please offer some help

**Comment by Renovamen** [comment]
应该是因为加载了与当前版本不兼容的模型权重文件。我之前更新了包版本，但没有上传最新的模型权重，所以会有这样的问题（但如果重新训练的话是没有问题的）。我现在已经把最新的模型权重上传到了 [checkpoints 文件夹](https://github.com/Renovamen/Speech-Emotion-Recognition/tree/master/checkpoints)，可以再试一下。感谢指出！

**Comment by zyb8543d** [comment]
> 应该是因为加载了与当前版本不兼容的模型权重文件。我之前更新了包版本，但没有上传最新的模型权重，所以会有这样的问题（但如果重新训练的话是没有问题的）。我现在已经把最新的模型权重上传到了 [checkpoints 文件夹](https://github.com/Renovamen/Speech-Emotion-Recognition/tree/master/checkpoints)，可以再试一下。感谢指出！

The error has been solved with your updates,but met other errors:
```
/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/sklearn/base.py:310: UserWarning: Trying to unpickle estimator StandardScaler from version 1.0.2 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
2022-04-20 14:08:06.870447: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2022-04-20 14:08:06.871543: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 2593905000 Hz
Traceback (most recent call last):
  File "predict.py", line 41, in <module>
    predict(config, audio_path, model)
  File "predict.py", line 29, in predict
    result = model.predict(test_feature)
  File "/home/ybZhang/.open_source/Speech-Emotion-Recognition/models/dnn/dnn.py", line 118, in predict
    return np.argmax(self.model.predict(samples), axis=1)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1727, in predict
    tmp_batch_outputs = self.predict_function(iterator)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1569 predict_function  *
        return step_function(self, iterator)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1559 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/distribute/distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1552 run_step  **
        outputs = model.predict_step(data)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:1525 predict_step
        return self(x, training=False)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    /home/ybZhang/miniconda3/envs/et/lib/python3.8/site-packages/tensorflow/python/keras/engine/input_spec.py:267 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) +

    ValueError: Input 0 is incompatible with layer sequential: expected shape=(None, None, 1582), found shape=(None, 1, 312)
```
