### ISSUE TITLE
single_feature.csv

### ISSUE THREAD

**Issue by pn1024** [Renovamen/Speech-Emotion-Recognition#30]
single_feature.csv这个文件可以传一个类似的文件吗？我想知道格式是什么样的

**Comment by ldqfalse** [comment]
我也是这里报错，求问大佬解决了吗

**Comment by ldqfalse** [comment]
> single_feature.csv这个文件可以传一个类似的文件吗？我想知道格式是什么样的

我也是这里报错，求问大佬解决了吗

**Comment by Renovamen** [comment]
已上传：[single_feature.csv](https://github.com/Renovamen/Speech-Emotion-Recognition/files/8643775/single_feature.csv)

---

single_feature.csv 是 opensmile 提取单个音频时生成的特征文件，参考 https://github.com/Renovamen/Speech-Emotion-Recognition/issues/3 。可以试一下直接在终端里运行 opensmile 抽取特征的命令：

https://github.com/Renovamen/Speech-Emotion-Recognition/blob/64e2f48be4ed0ed3fba3f85af824209f6c5c3884/extract_feats/opensmile.py#L42

如果成功，就会在你配置的路径下生成 single_feature.csv；如果报错，可以看一下是不是路径的问题，或者发一下报错信息？

**Comment by pn1024** [comment]
单个是没有问题，批处理就有问题

**Comment by YUZHIWANG-bug** [comment]
> 已上传：[single_feature.csv](https://github.com/Renovamen/Speech-Emotion-Recognition/files/8643775/single_feature.csv)
> 
> single_feature.csv 是 opensmile 提取单个音频时生成的特征文件，参考 #3 。可以试一下直接在终端里运行 opensmile 抽取特征的命令：
> 
> https://github.com/Renovamen/Speech-Emotion-Recognition/blob/64e2f48be4ed0ed3fba3f85af824209f6c5c3884/extract_feats/opensmile.py#L42
> 
> 如果成功，就会在你配置的路径下生成 single_feature.csv；如果报错，可以看一下是不是路径的问题，或者发一下报错信息？

请问作者，改如何配置opensmile呢，您使用的版本号是多少啊，如果不用opensmile，该怎么使用librosa啊

**Comment by Jinzeyuu** [comment]
你好，博主。我在特征提取运行opensmile.py和librosa.py，似乎是在plot.py这文件中调用display失败。问题如下：
Traceback (most recent call last):
  File "E:/emotion recognition/...Speech-Emotion-Recognition-master/extract_feats/opensmile.py", line 10, in <module>
    import utils
  File "E:\emotion recognition\...Speech-Emotion-Recognition-master\utils\__init__.py", line 2, in <module>
    from .plot import *
  File "E:\emotion recognition\...Speech-Emotion-Recognition-master\utils\plot.py", line 4, in <module>
    import librosa.display
ModuleNotFoundError: No module named 'librosa.display'; 'librosa' is not a package

**Comment by Jinzeyuu** [comment]
> 单个是没有问题，批处理就有问题

你好，问题解决了吗，我也没有批处理成功

**Comment by YUZHIWANG-bug** [comment]
> 你好，博主。我在特征提取运行opensmile.py和librosa.py，似乎是在plot.py这文件中调用display失败。问题如下： Traceback (most recent call last): File "E:/emotion recognition/...Speech-Emotion-Recognition-master/extract_feats/opensmile.py", line 10, in import utils File "E:\emotion recognition...Speech-Emotion-Recognition-master\utils__init__.py", line 2, in from .plot import * File "E:\emotion recognition...Speech-Emotion-Recognition-master\utils\plot.py", line 4, in import librosa.display ModuleNotFoundError: No module named 'librosa.display'; 'librosa' is not a package

你需要在windows或MacOS环境下配置librosa或opensmile，请注意修改opensmile.py里面的cmd = 'cd ' + config.opensmile_path + ' && ./SMILExtract -C ' + opensmile_config_path + ' -I ' + filepath + ' -O ' + single_feat_path + ' -appendarff 0' 命令，即可运行

**Comment by Jinzeyuu** [comment]
> 

请问要修改哪一个部分呢，我这两天一直在调特征提取这部分，实在不太懂，请大佬们指教

**Comment by YUZHIWANG-bug** [comment]
<img width="207" alt="image" src="https://github.com/Renovamen/Speech-Emotion-Recognition/assets/72587415/1f9bd453-af81-4780-9b3b-241a815c29cf">
请注意配置opensmile，以下是我的opensmile.py的修改，可以参照，注意读代码，然后修改predict即可。
# Opensmile 命令
    # cmd = 'cd ' + config.opensmile_path + ' && ./SMILExtract -C ' + opensmile_config_path + ' -I ' + filepath + ' -O ' + single_feat_path + ' -appendarff 0'
    # 尝试更改opensmile路径
    split_filepath = filepath.split('/')
    new_filepath = os.path.join(split_filepath[1], split_filepath[2])
    # cmd = 'cd ' + config.opensmile_path + ' && ./SMILExtract -C ' + opensmile_config_path + ' -I ' + 'sample/201_surprise.wav' + ' -O ' + single_feat_path + ' -appendarff 0'
    cmd = 'cd ' + config.opensmile_path + ' && ./bin/SMILExtract -C ' + 'config/is09-13/IS10_paraling.conf' + ' -I ' + filepath + ' -O ' + single_feat_path + ' -appendarff 0'
    # 可以不用手动更改了
    # 没办法在predict里面进行路径更改，只能在此进行！！！！！！
    # 这里预测音频的路径需手动更改，但是opensmile对于音频格式有要求，可能需要经过matlab处理

**Comment by YUZHIWANG-bug** [comment]
> > 
> 
> 请问要修改哪一个部分呢，我这两天一直在调特征提取这部分，实在不太懂，请大佬们指教

opensmile的配置参照CSDN，有详细教程，祝你成功运行。

**Comment by Jinzeyuu** [comment]
> > > 
> > 
> > 
> > 请问要修改哪一个部分呢，我这两天一直在调特征提取这部分，实在不太懂，请大佬们指教
> 
> opensmile的配置参照CSDN，有详细教程，祝你成功运行。

好的，谢谢，我可以加您个qq吗，有些问题想请教下1965782319

**Comment by xiao-xin-1** [comment]
> 你好，博主。我在特征提取运行opensmile.py和librosa.py，似乎是在plot.py这文件中调用display失败。问题如下： Traceback (most recent call last): File "E:/emotion recognition/...Speech-Emotion-Recognition-master/extract_feats/opensmile.py", line 10, in import utils File "E:\emotion recognition...Speech-Emotion-Recognition-master\utils__init__.py", line 2, in from .plot import * File "E:\emotion recognition...Speech-Emotion-Recognition-master\utils\plot.py", line 4, in import librosa.display ModuleNotFoundError: No module named 'librosa.display'; 'librosa' is not a package

我也是这个，请问解决了吗？

**Comment by pn1024** [comment]
换一个版本吧&nbsp; 好久之前的问题了&nbsp; librosa0.72试一下



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 7, 2024 20:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Renovamen/Speech-Emotion-Recognition] single_feature.csv (Issue#30)




  
你好，博主。我在特征提取运行opensmile.py和librosa.py，似乎是在plot.py这文件中调用display失败。问题如下： Traceback (most recent call last): File "E:/emotion recognition/...Speech-Emotion-Recognition-master/extract_feats/opensmile.py", line 10, in import utils File "E:\emotion recognition...Speech-Emotion-Recognition-master\utils__init__.py", line 2, in from .plot import * File "E:\emotion recognition...Speech-Emotion-Recognition-master\utils\plot.py", line 4, in import librosa.display ModuleNotFoundError: No module named 'librosa.display'; 'librosa' is not a package
  
我也是这个，请问解决了吗？
